services:
  # Database Service
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Reference env var

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 3
    networks:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources: # PostgreSQL
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          memory: 1G

  # Web Application Service
  web:
    build: .
    container_name: web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application --env DJANGO_SETTINGS_MODULE=config.settings.production"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.${DJANGO_ENV:-production}  # Environment-based config
      STREAM_CHAT_API_KEY: ${STREAM_CHAT_API_KEY} 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      POSTGRES_HOST: db
      PYTHONUNBUFFERED: 1
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - staticfiles:/app/staticfiles
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits: # Django/React
          cpus: '1.5'  # 1.5 cores max
          memory: 2G   # Hard memory limit
        reservations:
          memory: 512M # Guaranteed minimuming Service
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - web
    deploy:
      resources: # Monitoring
        limits:
          cpus: '0.3'
          memory: 512M

  # Reverse Proxy Service (HTTPS)
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - backend
    deploy:
      resources: # Reverse Proxy
        limits:
          cpus: '0.5'
          memory: 256M
volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  staticfiles:
    driver: local

networks:
  backend:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16