
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: real_estate
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d real_estate"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate;
             exec gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: real_estate
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: securepassword
      DJANGO_SETTINGS_MODULE: config.settings.production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: