# docker-compose.yml

services:
  # ----- Database Cluster -----
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}             # Set in .env
      POSTGRES_USER: ${POSTGRES_USER}         # Set in .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use secrets in production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # ----- Caching Layer -----
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} # HARDCODED: Set in .env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # ----- Application Server -----
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db --timeout 30 &&
            python manage.py migrate &&
            python manage.py collectstatic --no-input &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "${APP_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ----- Monitoring System -----
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - backend
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # ----- Reverse Proxy -----
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"    # HARDCODED: Remove in production if using cloud LB
      - "443:443"  # HARDCODED: Use cloud provider SSL termination in production
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:

networks:
  backend:
    driver: bridge

# ----- Security Enforcement -----
# 1. Required environment variables (.env):
#    - POSTGRES_PASSWORD
#    - REDIS_PASSWORD
#    - SECRET_KEY
# 2. Generate production SSL certificates:
#    openssl dhparam -out nginx/ssl/dhparam.pem 4096
# 3. Enable firewall (ports 443 only)