name: Django CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16  # Match your production version
        env:
          POSTGRES_DB: real_estate
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: securepassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - postgres_data:/var/lib/postgresql/data

    env:
      DATABASE_URL: postgresql://appuser:securepassword@localhost:5432/real_estate
      PYTHONPATH: ${{ github.workspace }}/apps:${{ github.workspace }}/config

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/dev.txt

    - name: Wait for database
      run: python manage.py wait_for_db

    - name: Run migrations
      run: python manage.py migrate --noinput

    - name: Run tests
      env:
        DEBUG: "True"
        SECRET_KEY: ${{ secrets.SECRET_KEY || 'test-secret-key' }}
        ALLOWED_HOSTS: "localhost"
      run: |
        python manage.py test apps.core apps.listings apps.users --noinput